-- AlterTable
ALTER TABLE `RefundRequest` DROP COLUMN `notes`,
    ADD COLUMN `adminNotes` TEXT NULL,
    ADD COLUMN `category` ENUM('ITEM_NOT_RECEIVED', 'ITEM_DAMAGED', 'WRONG_ITEM', 'QUALITY_ISSUE', 'DELIVERY_CANCELLED', 'DUPLICATE_ORDER', 'OTHER') NOT NULL DEFAULT 'OTHER',
    ADD COLUMN `initiatedBy` VARCHAR(191) NOT NULL DEFAULT 'CUSTOMER',
    ADD COLUMN `photoUrl` VARCHAR(191) NULL,
    ADD COLUMN `razorpayRefundId` VARCHAR(191) NULL,
    MODIFY `status` ENUM('REQUESTED', 'UNDER_REVIEW', 'APPROVED', 'PROCESSING', 'REFUNDED', 'REJECTED', 'CANCELLED') NOT NULL DEFAULT 'REQUESTED';

-- CreateIndex
CREATE INDEX `RefundRequest_status_idx` ON `RefundRequest`(`status`);

